"""End-to-end live verification against the running Neo4j graph + Ollama.

Proves the North Star: a natural-language threat question is answered using
context retrieved from the knowledge graph, generated by the local LLM, with a
grounding ratio. Run: python scripts/verify_e2e.py
"""
import sys, time, traceback
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config.settings import NEO4J_DATABASE, OLLAMA_MODEL, OLLAMA_ENDPOINT


def banner(t):
    print("\n" + "=" * 64 + f"\n  {t}\n" + "=" * 64)


def main():
    banner("STEP A - Graph connectivity")
    from src.services.knowledge_graph.neo4j_connection import verify_connectivity, run_query
    print(f"  DB={NEO4J_DATABASE}  model={OLLAMA_MODEL}  endpoint={OLLAMA_ENDPOINT}")
    if not verify_connectivity():
        print("  [FAIL] Neo4j not reachable"); return 1
    print("  [OK] Neo4j reachable")
    nodes = run_query("MATCH (n) RETURN count(n) AS c")[0]["c"]
    print(f"  [OK] node count: {nodes:,}")
    try:
        dist = run_query(
            "MATCH (f:Flow) WHERE f.label IS NOT NULL "
            "RETURN f.label AS label, count(*) AS c ORDER BY c DESC LIMIT 8")
        print("  Top attack labels:")
        for r in dist:
            print(f"     {r['label']:<24} {r['c']:,}")
    except Exception as e:
        print(f"  (label distribution query skipped: {e})")

    banner("STEP B - GraphRAG retrieval (no LLM)")
    from src.services.graphrag.retrievers import CypherRetriever, VectorGraphRetriever
    q = "DDoS TCP flood attack devices"
    t0 = time.time()
    cyp = CypherRetriever().retrieve(q)
    print(f"  [OK] Cypher retrieved {len(cyp.get('results', []))} items in {time.time()-t0:.1f}s")
    try:
        t0 = time.time()
        vec = VectorGraphRetriever().retrieve("DDoS TCP flood", search_type="attack")
        print(f"  [OK] Vector retrieved {len(vec.get('results', []))} items in {time.time()-t0:.1f}s")
    except Exception as e:
        print(f"  [warn] vector retrieval unavailable ({type(e).__name__}: {str(e)[:80]}); LLM will use Cypher context")

    banner("STEP C - Live LLM threat explanation + grounding")
    from src.services.threat_explanation.explainer import ThreatExplainer
    explainer = ThreatExplainer()
    t0 = time.time()
    result = explainer.explain_attack("DDoS-TCP_Flood")
    dt = time.time() - t0
    analysis = result.get("analysis", "")
    print(f"  [OK] LLM responded in {dt:.0f}s; grounding_ratio={result.get('grounding_ratio')}")
    print(f"  ungrounded (sample): {result.get('ungrounded_entities', [])[:5]}")
    print("\n  --- ANALYSIS (first 1200 chars) ---")
    print("\n".join("  " + ln for ln in analysis[:1200].splitlines()))

    banner("STEP D - Free-form investigation query")
    t0 = time.time()
    inv = explainer.investigate("Which devices show Mirai botnet behavior and what protocols do they use?")
    print(f"  [OK] investigate() responded in {time.time()-t0:.0f}s")
    print("\n  --- ANSWER (first 900 chars) ---")
    print("\n".join("  " + ln for ln in inv.get("analysis", "")[:900].splitlines()))

    banner("END-TO-END: PASS")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        traceback.print_exc()
        sys.exit(1)
